<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Modules\Showcase\app\Enum\ShowcasePriorityEnum;
use Modules\Showcase\app\Enum\ShowcaseStatusEnum;
use Modules\Showcase\app\Enum\ShowcaseVisibilityEnum;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('showcases', function (Blueprint $table) {
            $table->id();
            $table->foreignId('showcase_category_id')->constrained('showcase_categories')->cascadeOnDelete();
            // Human-readable identifier generated by ShowcaseObserver on create.
            $table->string('reference')->unique();
            $table->mediumText('name');
            $table->mediumText('description')->nullable();
            $table->string('cover')->nullable();

            // Enum-backed columns are stored as strings, never as a native enum column.
            $table->string('status')->default(ShowcaseStatusEnum::default());
            $table->string('priority')->default(ShowcasePriorityEnum::default());
            $table->string('visibility')->default(ShowcaseVisibilityEnum::default());

            $table->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();
            $table->decimal('rating', 3, 2)->nullable();
            $table->unsignedInteger('views_count')->default(0);
            $table->unsignedInteger('sort_order')->default(0);
            $table->json('metadata')->nullable();
            $table->dateTime('published_at')->nullable();
            // Business date the reminder/calendar notification channels hang off.
            $table->dateTime('expires_at')->nullable();
            $table->boolean('is_active')->default(1);
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('deleted_by')->nullable()->constrained('users')->nullOnDelete();
            $table->softDeletes();
            $table->timestamps();

            $table->index(['status', 'is_active']);
            $table->index(['visibility', 'published_at']);
            $table->index(['showcase_category_id', 'sort_order']);
            $table->index('expires_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('showcases');
    }
};
