<?php

return [

    'greetings' => [
        'egyptian' => [
            'ازيك',
            'ازايك',
            'عامل ايه',
            'اخبارك ايه',
            'ايه الاخبار',
            'الدنيا ايه',
            'ايه النظام',
            'عاملين ايه',
            'تمام',
            'الحمد لله',
        ],

        'saudi' => [
            'هلا',
            'يا هلا',
            'هلا والله',
            'مرحبا',
            'يا مرحبا',
            'وش اخبارك',
            'وش علومك',
            'كيفك',
            'كيف الحال',
            'ايش اخبارك',
            'شخبارك',
            'علومك',
            'عساك طيب',
            'حي الله',
            'الله يحييك',
            'يا هلا وغلا',
        ],

        'english' => [
            'hi',
            'hello',
            'hey',
            'how are you',
            'what is up',
            'whats up',
            'good morning',
            'good evening',
        ],
    ],

    'live_data' => [
        'count' => [
            'how many',
            'count',
            'count of',
            'number of',
            'total',
            'كام',
            'كم',
            'عدد',
            'اجمالي',
            'مجموع',
        ],

        'latest' => [
            'latest',
            'recent',
            'newest',
            'last',
            'اخر',
            'احدث',
            'جديد',
            'اخر مستخدمين',
            'احدث مستخدمين',
        ],

        'top' => [
            'top',
            'highest',
            'most',
            'best',
            'اكتر',
            'اكثر',
            'اعلى',
            'افضل',
        ],

        'search' => [
            'search',
            'find',
            'look for',
            'دور',
            'ابحث',
            'بحث',
            'فتش',
            'هات',
            'اظهر',
        ],

        'summary' => [
            'summary',
            'summarize',
            'overview',
            'stats',
            'statistics',
            'ملخص',
            'لخص',
            'نبذه',
            'احصائيات',
            'تقرير',
        ],

        'compare' => [
            'compare',
            'vs',
            'versus',
            'difference',
            'قارن',
            'مقارنه',
            'الفرق بين',
        ],
    ],

    'knowledge' => [
        'اشرح',
        'اشرحلي',
        'ازاي',
        'كيف',
        'ايه شروط',
        'ما شروط',
        'ايه قواعد',
        'سياسه',
        'policy',
        'rules',
        'docs',
        'documentation',
        'readme',
        'how does',
        'how do',
        'what are the',
        'what is the',
    ],

    'project_structure' => [
        'فين',
        'مكان',
        'اي ملف',
        'انهي ملف',
        'which file',
        'which service',
        'which controller',
        'route',
        'controller',
        'service',
        'model',
        'architecture',
        'structure',
    ],

    'memory_references' => [
        'كمل اللي فات',
        'كمل اللي قلته',
        'كمل التقرير اللي قولتلك عليه',
        'زي ما قلتلك',
        'زي ما قولتلك',
        'قبل كده',
        'المرة اللي فاتت',
        'فاكر التقرير',
        'فاكر اللي قولته',
        'continue what we discussed',
        'as we discussed',
        'we talked about',
        'last time',
        'like before',
        'from before',
        'previous conversation',
    ],

    'complex_analytics' => [
        'compare',
        'vs',
        'versus',
        'difference between',
        'relationship',
        'correlation',
        'trend',
        'over time',
        'month over month',
        'year over year',
        'قارن',
        'مقارنه',
        'الفرق بين',
        'اتجاه',
        'ترند',
        'نمو',
        'انخفاض',
        'ارتفاع',
        'شهر بشهر',
        'سنه بسنه',
    ],

    'business_rule_indicators' => [
        'rules',
        'policy',
        'calculated',
        'calculation',
        'بيتحسب',
        'قواعد',
        'سياسه',
        'شروط',
        'من paid',
        'من المدفوع',
    ],

    'action_synonyms' => [
        'count' => [
            'how many',
            'number of',
            'count',
            'count of',
            'total',
            'كام',
            'كم',
            'عدد',
            'اجمالي',
            'مجموع',
        ],
        'search' => [
            'search',
            'find',
            'lookup',
            'filter',
            'where',
            'دور',
            'ابحث',
            'بحث',
            'فتش',
            'هات',
            'اظهر',
        ],
        'latest' => [
            'latest',
            'recent',
            'newest',
            'last',
            'new',
            'اخر',
            'احدث',
            'جديد',
        ],
        'top' => [
            'top',
            'highest',
            'most',
            'best',
            'اكتر',
            'اكثر',
            'اعلى',
            'افضل',
        ],
        'stats' => [
            'stats',
            'statistics',
            'analytics',
            'overview',
            'احصائيات',
            'تحليلات',
            'ارقام',
        ],
        'summary' => [
            'summary',
            'summarize',
            'overview',
            'ملخص',
            'لخص',
            'نبذه',
            'تقرير',
        ],
        'compare' => [
            'compare',
            'vs',
            'versus',
            'difference',
            'قارن',
            'مقارنه',
            'الفرق بين',
        ],
    ],
];
