<?php

/**
 * Resolve a translation key using the application's default (active) locale.
 */
$t = static fn (string $key): string => trans("form::validations.{$key}");

$ruleSchemas = [
    'min' => [
        [
            'name' => 'value',
            'type' => 'number',
            'label' => $t('label_minimum_value'),
            'placeholder' => $t('enter_minimum_value'),
            'default' => 0,
            'rules' => [
                'required',
                'numeric',
                'min:0',
            ],
        ],
    ],
    'max' => [
        [
            'name' => 'value',
            'type' => 'number',
            'label' => $t('label_maximum_value'),
            'placeholder' => $t('enter_maximum_value'),
            'default' => 0,
            'rules' => [
                'required',
                'numeric',
                'min:0',
            ],
        ],
    ],
    'size' => [
        [
            'name' => 'value',
            'type' => 'number',
            'label' => $t('label_size'),
            'placeholder' => $t('enter_size_value'),
            'default' => 0,
            'rules' => [
                'required',
                'numeric',
                'min:0',
            ],
        ],
    ],
    'regex' => [
        [
            'name' => 'pattern',
            'type' => 'text',
            'label' => $t('label_regex_pattern'),
            'placeholder' => $t('enter_regex_pattern'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'unique' => [
        [
            'name' => 'table',
            'type' => 'text',
            'label' => $t('label_table_name'),
            'placeholder' => $t('enter_table_name_example'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
        [
            'name' => 'column',
            'type' => 'text',
            'label' => $t('label_column_name'),
            'placeholder' => $t('enter_column_name_optional'),
            'default' => null,
            'rules' => [
                'nullable',
                'string',
            ],
        ],
        [
            'name' => 'ignore_id',
            'type' => 'text',
            'label' => $t('label_ignore_id'),
            'placeholder' => $t('id_to_ignore'),
            'default' => null,
            'rules' => [
                'nullable',
            ],
        ],
        [
            'name' => 'ignore_column',
            'type' => 'text',
            'label' => $t('label_ignore_column'),
            'placeholder' => $t('column_for_ignore_condition'),
            'default' => null,
            'rules' => [
                'nullable',
                'string',
            ],
        ],
    ],
    'exists' => [
        [
            'name' => 'table',
            'type' => 'text',
            'label' => $t('label_table_name'),
            'placeholder' => $t('enter_table_name'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
        [
            'name' => 'column',
            'type' => 'text',
            'label' => $t('label_column_name'),
            'placeholder' => $t('enter_column_name_optional'),
            'default' => null,
            'rules' => [
                'nullable',
                'string',
            ],
        ],
    ],
    'in' => [
        [
            'name' => 'values',
            'type' => 'textarea',
            'label' => $t('label_allowed_values'),
            'placeholder' => $t('enter_comma_separated_values_example'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'not_in' => [
        [
            'name' => 'values',
            'type' => 'textarea',
            'label' => $t('label_excluded_values'),
            'placeholder' => $t('enter_comma_separated_values_to_exclude'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'starts_with' => [
        [
            'name' => 'values',
            'type' => 'textarea',
            'label' => $t('label_starting_values'),
            'placeholder' => $t('enter_comma_separated_values'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'ends_with' => [
        [
            'name' => 'values',
            'type' => 'textarea',
            'label' => $t('label_ending_values'),
            'placeholder' => $t('enter_comma_separated_values'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'between' => [
        [
            'name' => 'min',
            'type' => 'number',
            'label' => $t('label_minimum_value'),
            'placeholder' => $t('enter_minimum_value'),
            'default' => 0,
            'rules' => [
                'required',
                'numeric',
            ],
        ],
        [
            'name' => 'max',
            'type' => 'number',
            'label' => $t('label_maximum_value'),
            'placeholder' => $t('enter_maximum_value'),
            'default' => 0,
            'rules' => [
                'required',
                'numeric',
            ],
        ],
    ],
    'digits' => [
        [
            'name' => 'value',
            'type' => 'number',
            'label' => $t('label_number_of_digits'),
            'placeholder' => $t('enter_number_of_digits'),
            'default' => 0,
            'rules' => [
                'required',
                'integer',
                'min:1',
            ],
        ],
    ],
    'digits_between' => [
        [
            'name' => 'min',
            'type' => 'number',
            'label' => $t('label_minimum_digits'),
            'placeholder' => $t('enter_minimum_digits'),
            'default' => 0,
            'rules' => [
                'required',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'max',
            'type' => 'number',
            'label' => $t('label_maximum_digits'),
            'placeholder' => $t('enter_maximum_digits'),
            'default' => 0,
            'rules' => [
                'required',
                'integer',
                'min:1',
            ],
        ],
    ],
    'decimal' => [
        [
            'name' => 'min_places',
            'type' => 'number',
            'label' => $t('label_minimum_decimal_places'),
            'placeholder' => $t('enter_minimum_decimal_places'),
            'default' => 0,
            'rules' => [
                'required',
                'integer',
                'min:0',
            ],
        ],
        [
            'name' => 'max_places',
            'type' => 'number',
            'label' => $t('label_maximum_decimal_places'),
            'placeholder' => $t('enter_maximum_decimal_places'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:0',
            ],
        ],
    ],
    'gt' => [
        [
            'name' => 'field',
            'type' => 'text',
            'label' => $t('label_field_name'),
            'placeholder' => $t('enter_field_name_to_compare'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'gte' => [
        [
            'name' => 'field',
            'type' => 'text',
            'label' => $t('label_field_name'),
            'placeholder' => $t('enter_field_name_to_compare'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'lt' => [
        [
            'name' => 'field',
            'type' => 'text',
            'label' => $t('label_field_name'),
            'placeholder' => $t('enter_field_name_to_compare'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'lte' => [
        [
            'name' => 'field',
            'type' => 'text',
            'label' => $t('label_field_name'),
            'placeholder' => $t('enter_field_name_to_compare'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'date_format' => [
        [
            'name' => 'format',
            'type' => 'select',
            'label' => $t('label_date_format'),
            'placeholder' => $t('select_date_format'),
            'default' => 'Y-m-d',
            'options' => [
                'Y-m-d',
                'd/m/Y',
                'm/d/Y',
                'Y-m-d H:i:s',
                'Y-m-d H:i',
                'H:i:s',
                'H:i',
            ],
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'after' => [
        [
            'name' => 'date',
            'type' => 'text',
            'label' => $t('label_after_date_field'),
            'placeholder' => $t('enter_date_or_field_name'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'after_or_equal' => [
        [
            'name' => 'date',
            'type' => 'text',
            'label' => $t('label_after_or_equal_date_field'),
            'placeholder' => $t('enter_date_or_field_name'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'before' => [
        [
            'name' => 'date',
            'type' => 'text',
            'label' => $t('label_before_date_field'),
            'placeholder' => $t('enter_date_or_field_name'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'before_or_equal' => [
        [
            'name' => 'date',
            'type' => 'text',
            'label' => $t('label_before_or_equal_date_field'),
            'placeholder' => $t('enter_date_or_field_name'),
            'default' => '',
            'rules' => [
                'required',
                'string',
            ],
        ],
    ],
    'mimes' => [
        [
            'name' => 'extensions',
            'type' => 'select',
            'label' => $t('label_file_extensions'),
            'placeholder' => $t('select_allowed_extensions'),
            'default' => [],
            'multiple' => true,
            'options' => [
                'jpg',
                'jpeg',
                'png',
                'gif',
                'webp',
                'svg',
                'pdf',
                'doc',
                'docx',
                'xls',
                'xlsx',
                'csv',
                'txt',
                'zip',
                'rar',
                'mp4',
                'mp3',
            ],
            'rules' => [
                'required',
                'array',
                'min:1',
            ],
        ],
    ],
    'mimetypes' => [
        [
            'name' => 'types',
            'type' => 'select',
            'label' => $t('label_mime_types'),
            'placeholder' => $t('select_allowed_mime_types'),
            'default' => [],
            'multiple' => true,
            'options' => [
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'image/svg+xml',
                'application/pdf',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'application/vnd.ms-excel',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'text/plain',
                'text/csv',
                'application/zip',
                'video/mp4',
                'audio/mpeg',
            ],
            'rules' => [
                'required',
                'array',
                'min:1',
            ],
        ],
    ],
    'dimensions' => [
        [
            'name' => 'min_width',
            'type' => 'number',
            'label' => $t('label_minimum_width'),
            'placeholder' => $t('enter_minimum_width_pixels'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'max_width',
            'type' => 'number',
            'label' => $t('label_maximum_width'),
            'placeholder' => $t('enter_maximum_width_pixels'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'min_height',
            'type' => 'number',
            'label' => $t('label_minimum_height'),
            'placeholder' => $t('enter_minimum_height_pixels'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'max_height',
            'type' => 'number',
            'label' => $t('label_maximum_height'),
            'placeholder' => $t('enter_maximum_height_pixels'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'width',
            'type' => 'number',
            'label' => $t('label_exact_width'),
            'placeholder' => $t('enter_exact_width_pixels'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'height',
            'type' => 'number',
            'label' => $t('label_exact_height'),
            'placeholder' => $t('enter_exact_height_pixels'),
            'default' => null,
            'rules' => [
                'nullable',
                'integer',
                'min:1',
            ],
        ],
        [
            'name' => 'ratio',
            'type' => 'text',
            'label' => $t('label_aspect_ratio'),
            'placeholder' => $t('enter_ratio'),
            'default' => null,
            'rules' => [
                'nullable',
                'string',
            ],
        ],
    ],
];

$fields = [
    [
        'type' => 'text',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'string',
            'min',
            'max',
            'size',
            'alpha',
            'alpha_num',
            'alpha_dash',
            'regex',
            'unique',
            'exists',
            'in',
            'not_in',
            'starts_with',
            'ends_with',
            'lowercase',
            'uppercase',
        ],
    ],
    [
        'type' => 'textarea',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'string',
            'min',
            'max',
            'size',
            'regex',
        ],
    ],
    [
        'type' => 'number',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'integer',
            'numeric',
            'min',
            'max',
            'between',
            'digits',
            'digits_between',
            'decimal',
            'gt',
            'gte',
            'lt',
            'lte',
        ],
    ],
    [
        'type' => 'email',
        'multiple' => true,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'email',
            'unique',
            'exists',
        ],
    ],
    [
        'type' => 'password',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'string',
            'min',
            'max',
            'confirmed',
            'regex',
        ],
    ],
    [
        'type' => 'tel',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'string',
            'min',
            'max',
            'regex',
            'unique',
        ],
    ],
    [
        'type' => 'url',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'url',
            'active_url',
        ],
    ],
    [
        'type' => 'date',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'date',
            'date_format',
            'after',
            'after_or_equal',
            'before',
            'before_or_equal',
        ],
    ],
    [
        'type' => 'datetime-local',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'date',
            'date_format',
            'after',
            'after_or_equal',
            'before',
            'before_or_equal',
        ],
    ],
    [
        'type' => 'time',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'date_format',
        ],
    ],
    [
        'type' => 'select',
        'multiple' => true,
        'has_options' => true,
        'rules' => [
            'required',
            'nullable',
            'in',
            'not_in',
            'exists',
        ],
    ],
    [
        'type' => 'radio',
        'multiple' => null,
        'has_options' => true,
        'rules' => [
            'required',
            'nullable',
            'in',
        ],
    ],
    [
        'type' => 'checkbox',
        'multiple' => true,
        'has_options' => true,
        'rules' => [
            'required',
            'nullable',
            'accepted',
            'declined',
            'boolean',
            'in',
            'array',
            'min',
            'max',
        ],
    ],
    [
        'type' => 'file',
        'multiple' => true,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'file',
            'mimes',
            'mimetypes',
            'min',
            'max',
            'between',
        ],
    ],
    [
        'type' => 'image',
        'multiple' => true,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'image',
            'mimes',
            'mimetypes',
            'min',
            'max',
            'dimensions',
        ],
    ],
    [
        'type' => 'color',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'regex',
        ],
    ],
    [
        'type' => 'range',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'numeric',
            'min',
            'max',
            'between',
        ],
    ],
    [
        'type' => 'hidden',
        'multiple' => null,
        'has_options' => null,
        'rules' => [
            'required',
            'nullable',
            'string',
            'integer',
        ],
    ],
];

$buildRules = static fn (array $rules): array => array_map(
    static fn (string $rule): array => [
        'name' => $rule,
        'label' => $t("rule_{$rule}"),
        'schema' => $ruleSchemas[$rule] ?? [],
    ],
    $rules,
);

return array_map(
    static fn (array $field): array => [
        'type' => $field['type'],
        'multiple' => $field['multiple'],
        'has_options' => $field['has_options'],
        'rules' => $buildRules($field['rules']),
    ],
    $fields,
);
